apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: observability-lab
  labels:
    release: {{ .Values.monitorRelease }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/part-of: observability-lab
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
    honorLabels: true
