apiVersion: constraints.gatekeeper.sh/v1beta1
kind: DocsApprovedImages
metadata:
  name: approved-images
spec:
  enforcementAction: dryrun
  match:
    kinds:
    - apiGroups:
      - ''
      kinds:
      - Pod
    namespaces:
    - policy-lab
  parameters:
    prefixes:
    - registry.example.com/team/
