replicas: 3
auditInterval: 60
constraintViolationsLimit: 20
logLevel: INFO
validatingWebhookFailurePolicy: Ignore
mutatingWebhookFailurePolicy: Ignore
controllerManager:
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      memory: 512Mi
audit:
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      memory: 512Mi
